lib/Model.php
test/ActiveRecordTest.php
test/RelationshipTest.php

Fix for https://github.com/php-activerecord/activerecord/issues/8
See also:
https://github.com/jpfuentes2/php-activerecord/issues/156
http://www.phpactiverecord.org/boards/4/topics/1678-php-ar-and-twig
The issue is that the `__isset` magic method in `Model` only checks its own `$attributes` and `$alias_attributes` properties and doesn't consider other possibilities, such as magic getters and relationships. I'm using a fix proposed by @dfyx that handles these use cases. Thanks, @dfyx!
* added checks to `__isset` for getters and relationships
* expanded existing `test_isset` test to check a relationship 
* removed an assert from `RelationShipTest::test_eager_loading_has_many_array_of_includes`. It was no longer passing with the fix for `__isset`, and it didn't seem to provide any value as …

Fix isset for relationships

---

README.md

A working link to the documentation site in progress is better than the existing 404 link

Fixed Issue #18: Documentation link is broken in readme.md

---

lib/Model.php
lib/Relationship.php
lib/Validations.php

Fixed issue #23:
Creation of dynamic property ActiveRecord\Validations::$klass fixed by declaring the variable at the top of the class. 
Deprecated: Use of "static" in callables is deprecated fixed by using the static::class magic keyword.

Fix deprecation warnings in PHP 8.2

---

lib/Model.php

My apologies; I should have done a search in the repository of 'static:: to find all instances of this deprecation error. There's one more in Model.last(). Found and fixed.

A cleaner PR

---

lib/Model.php

Fix for issue #29 as per https://php.watch/versions/8.2/$%7Bvar%7D-string-interpolation-deprecated

Fixed using ${var} in strings is deprecated in PHP 8.2

---

CONTRIBUTING.md
README.md
lib/Relationship.php
phpunit.xml.dist
test/ActiveRecordTest.php
test/ActiveRecordWriteTest.php
test/CallbackTest.php
test/ColumnTest.php
test/ConfigTest.php
test/ConnectionManagerTest.php
test/DateTimeTest.php
test/InflectorTest.php
test/ModelCallbackTest.php
test/SQLBuilderTest.php
test/UtilsTest.php

- Updated documentation to remove support for Oracle since the tests no longer test it
- Moved some developer-specific documentation from readme.md to contributing.md
- Fixed PHP 8.2 deprecation errors in running the tests
- Upgraded phpunit.xml.dist to remove deprecation warning

Fix test deprecations

---

test/ActiveRecordTest.php
test/SerializationTest.php
test/fixtures/books.csv
test/models/Book.php
test/sql/mysql.sql
test/sql/pgsql.sql
test/sql/sqlite.sql

Some of the tests around `Book` were getting pretty difficult to understand. This is an attempt to simplify them a bit.

clean up tests and book class in particular

---

lib/Model.php
lib/PhpStan/FindDynamicMethodReturnTypeReflection.php
phpstan.neon.dist
test/ActiveRecordFindTest.php
test/phpstan/PhpStanReflectionTests.php

Adding a PHPStan extension so that the various return types of `Model::find`  can be statically checked.
In other words, if you're a PHPStan user, the following snippets will now all pass analysis without errors:
```php
/**
* Static checking for single model
*/
$book = Book::find(1);
assert($book instanceof Book);
$book = Book::find(['name'=>'Ubik']);
assert($book instanceof Book);
/**
* Static checking for nullable single model
*/
$book = Book::find('first', ['name'=>'Waldo']);
assert(is_null($book));
$book = Book::find('last', ['name'=>'Waldo']);
assert(is_null($book));
/**
* Static checking for array of models
*/
$books = Book::find(
'all',
['name' => 'William']
);
assert(0==count($books));
$books = Book::find(1, 3, 8);
assert(0==count($books));
$books = Book::find([1, 3, 8]); …
```

dynamic stan extension for Model::find

---

lib/PhpStan/ModelMethodsClassReflectionExtension.php
lib/PhpStan/ModelStaticMethodReflection.php
test/phpstan/DynamicCountBy.php

Static checking for `Model::count_by` magic method.
```php
use test\models\Book;
$numBooks = Book::count_by_name('Walden');
assert(is_int($numBooks));
```
...now passes static analysis.

static checking for count_by

---

examples/orders/models/Order.php
examples/orders/models/Payment.php
examples/orders/models/Person.php
lib/Model.php
lib/PhpStan/FindDynamicMethodReturnTypeReflection.php
lib/Relationship/AbstractRelationship.php
lib/Relationship/BelongsTo.php
lib/Relationship/HasAndBelongsToMany.php
lib/Relationship/HasMany.php
lib/Table.php
lib/Types.php
test/ActiveRecordFindTest.php
test/RelationshipTest.php
test/SerializationTest.php
test/helpers/foo.php
test/models/Amenity.php
test/models/Author.php
test/models/AuthorAttrAccessible.php
test/models/AwesomePerson.php
test/models/Book.php
test/models/BookAttrProtected.php
test/models/Event.php
test/models/Host.php
test/models/Property.php
test/models/PropertyAmenity.php
test/models/Venue.php
test/models/namespacetest/Book.php
test/phpstan/DynamicFInd.php

Reorganizing `Model::$belongs_to` and `Model::$has_one` from this:
```php
public static $has_many = [
['payments'],
['people',
'through'    => 'payments',
'select'     => 'people.*, payments.amount',
'conditions' => 'payments.amount < 200']];
```
to this:
```php
public static array $has_many = [
'payments' => true,
'people' => [
'through'    => 'payments',
'select'     => 'people.*, payments.amount',
'conditions' => 'payments.amount < 200'
]
];
```
This makes static checking on the options possible, and easier to read IMO.
TODO: a lot of the tests rely on static members like `Model::$belongs_to`, `Model::$has_one`, and so on. Some of the tests would try to cache and restore the state of these, others would append, still others would reset, which can lead to chaos. I think what we need to …

Reorganize Model::$belongs_to, Model::$has_one

---

lib/Model.php
lib/Table.php
lib/Types.php
test/ActiveRecordTest.php
test/DelegateTest.php
test/models/Event.php
test/phpstan/DynamicFInd.php

Fix for: https://github.com/php-activerecord/activerecord/issues/51
It turns out that all the delegate processing stuff in `Table` was just transforming the mixed array structure into one that is easier to read and deal with, so I just adopted the prettier structure as the formal API shape, and then I was able to kill off that section of code and make the configuration statically checkable in the same step. That also killed the need for the `processed` flag.

clean up static delegate prop

---

lib/Model.php
lib/Relationship/HasOne.php
lib/Table.php
test/RelationshipTest.php
test/models/Author.php
test/models/AuthorAttrAccessible.php
test/models/Book.php
test/models/Employee.php

Convert `Model::$has_one` to a `array<string,HasManyOptions>` format.

simplify has_one

---

.github/workflows/static-analysis.yml
.github/workflows/style.yml
.github/workflows/test.yml
README.md

Splitting apart the CI tasks a bit.

split workflow

---

lib/Connection.php
lib/Model.php
lib/Relation.php
lib/SQLBuilder.php
lib/Table.php
lib/Types.php
test/ActiveRecordCountTest.php
test/ActiveRecordFindTest.php
test/ActiveRecordPluckTest.php
test/ActiveRecordTest.php
test/ActiveRecordWriteTest.php
test/MysqlAdapterTest.php
test/RelationTest.php
test/SqliteAdapterTest.php
test/fixtures/authors.csv
test/helpers/AdapterTestCase.php

With this change, `pluck` works more like the Rails implementation, in that we talk directly to the database and no models are created.
Also:
* converted `Connection::query_and_fetch` to return a generator so we can clean up all the ugly callback stuff
* added `Relation::distinct()`

Optimize pluck, simplify stuff

---

lib/Model.php
lib/Relationship/AbstractRelationship.php
lib/Relationship/HasAndBelongsToMany.php
lib/Table.php
lib/Types.php
test/RelationshipTest.php
test/fixtures/courses.csv
test/fixtures/courses_students.csv
test/fixtures/students.csv
test/models/Course.php
test/models/Student.php
test/sql/mysql.sql
test/sql/pgsql.sql
test/sql/sqlite.sql

An attempt at implementing `HasAndBelongsToMany` (which was marked with "TODO: implement" in the original code, and evidently never completed) functionality:
* create new Student and Courses fixtures (every student attends many courses, every course is attended by many students)
* remove `get_relationship` stuff from `RelationshipTest` (a horrible anti-pattern, IMO)
* create `HasManyAndBelongsToMany` type, and convert to a `array<string, HasManyAndBelongsToMany>` format (for easier static checking)
Note that this is just the read part of this; I'm not sure what to do about writes, because as far as I can tell none of the other relationship classes currently support writes (ie `build` and `create` don't actually create new records).

Start on HasAndBelongsToMany

---

lib/Connection.php
lib/Model.php
lib/Relationship/HasMany.php
lib/cache/Memcache.php
test/ConnectionTest.php
test/RelationshipTest.php

Some more scattered attempts to increase coverage:
* replace unused `throws` with assert statements
* create `Connection::data_source_name` to exercise unix socket stuff in tests
* test for `create_association`

increase cov in Connection, remove unused

---

lib/Cache.php
lib/Column.php
lib/Connection.php
lib/ConnectionManager.php
test/helpers/AdapterTestCase.php

use asserts

---

lib/Model.php
lib/Relation.php
lib/SQLBuilder.php
lib/Table.php
test/ActiveRecordWriteTest.php
test/SQLBuilderTest.php
test/helpers/config.php

Removing the concept of passing conditions to `Model`:
* moved `delete_all` to `Relation`
* changed `Table::delete` to work more similarly to `Table::find`.
Since it now chains off of `Where` like anything else, I was able to remove all the tests that were exercising different args `delete_all`.

move delete_all to relation

---

lib/Validations.php

More coverage twiddling.
For this one, I also rejiggered `Validations` a bit so that it does a bit less reflection work. I have no idea if it will affect performance, but it reduces complexity.

improve coverage

---

lib/Cache.php
lib/cache/Memcache.php
lib/cache/iCache.php

When I was setting up all the typehints for the 2.0 refresh, I annotated  `Cache::$adapter` with `Memcache`.
This was a mistake, because clients will likely use their own cache implementation. In this change, I introduce an `iCache` interface which should be much more friendly. In the future we may want to move to some [kind of standard](https://www.php-fig.org/psr/psr-6/), but no need to get involved in that, now.

add interface for cache

---

README.md
lib/Column.php
lib/Config.php
lib/Connection.php
lib/Model.php
lib/PhpStan/Relation/RelationReflectionHelper.php
lib/Relation.php
test/ActiveRecordPHPStanTest.php
test/helpers/config.php
test/phpstan/RelationFindDynamicReturn.php

I spent the evening trying to integrate the 2.0 stuff into my private project, and wound up having to fix several little issues that didn't come up before:
* fixed several typos
* handle the case that client doesn't supply a logger
* fixed docs for `Model::find`
* greatly simplified the dynamic return extension stuff (before, it only detected array type if the one-and-only argument was a `ConstArrayType`, now it only decides an array if trinary `YES` and anything else (`NO` or `MAYBE` ) is interpreted to be a single.
* removed the dependency on `bccomp`, and added PHPStan ignore statement for the weird out-of-range int checking trick.
I still have at least one issue around `bccomp` to sort out, but otherwise everything was pretty simple and took only a few hours to port over (with much of …

Integration fixes

---

lib/Model.php
lib/Relation.php
lib/SQLBuilder.php
lib/Table.php
test/ActiveRecordWriteTest.php

Fix for #102 
Modernize `Model::update_all`, meaning that it no longer takes a big hairy argument with `conditions` and `set` and whatnot--now you can use it in conjunction with `where`, the same as everything else.

Modernize Model::update_all

---

lib/WhereClause.php

I think the intent here is correct; if you pass in an empty array, then it should equate to checking for `null`, but as far as I can tell this logic has always been unreachable, because we currently throw an exception if the number of vars doesn't match the number of `?` tokens. Can revisit someday.

remove unused logic

---

lib/Adapter/PgsqlAdapter.php
lib/Connection.php
lib/SQLBuilder.php

Reorganize a bit in an attempt to increase coverage.

rejigger things to increase coverage

---

lib/Table.php

Getting occasional run-time errors around the code that sets db_name on `Table`.

alternate syntax

---

UPGRADE.md
composer.json
lib/Relation.php
lib/Table.php
test/ActiveRecordFindTest.php

If I understand correctly, Rails throws a `RecordNotFound` exception when you pass an empty array to `find`, and we don't seem to be doing that. I still have a little more research to do, but opening a PR in the meantime.
Also, there are a few points in the code where we retrieve static members from classes via reflection that may or may not exist, and this was throwing warnings.

throw RecordNotFound on empty find

---

composer.json
lib/WhereClause.php
test/ActiveRecordFindTest.php
test/WhereClauseTest.php

Another subtle fix. Apparently, rails does not throw an exception if you do a `where` with an empty array. Both of these should return an empty array, not throw:
```php
Author::where(['author_id IN(?)', []])->to_a();
```
```php
Author::where(['author_id' => []])->to_a();
```
Rails optimize this under the hood by just doing an always-false clause, ie:
```
WHERE 1=0
```

simplify count

---

lib/Table.php

don't collect models if not needed

---

composer.json
lib/Model.php

`Model::delete` was implemented in such a way that multiple primary keys were not being considered when constructing its where, which led to deleting more than was intended. Whoops.

fix pk usage

---

lib/Relationship/AbstractRelationship.php
lib/Relationship/HasAndBelongsToMany.php
lib/Table.php
test/RelationshipTest.php

#126 Has and belongs to many ignores class_name
